import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.2.8',
  date: '2022-02-09T01:15:55.606Z',
};
export default meta;
