import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.2.10',
  date: '2022-02-15T05:36:58.217Z',
};
export default meta;
